import type { ControlAction } from "./control-center";

export const ACTIONS: ControlAction[] = [
  {
    id: "doctor",
    name: "Check Readiness",
    purpose: "See whether the local machine is ready to use.",
    why: "Use this first before starting the app or repairing the database.",
    effect: "Read only. It does not change files, the database, or services.",
    expected:
      "A READY, NOT READY, or REJECTED report for Node, pnpm, Git, Docker, the environment file, the database, and Prisma.",
    next: "If anything is not ready, follow the recovery written in the report.",
    command: "pnpm run doctor",
    source: "package.json → tools/doctor",
    category: "system",
    risk: "R0",
    safety: "safe",
    mutation: false,
    approval: "Not required. Read-only operation.",
    timeout: "A few seconds until the Docker engine responds.",
    executableHere: false,
    confirmation:
      "This action only reads. It must still be run on the local machine, not from this board.",
  },
  {
    id: "status",
    name: "Review Governance Status",
    purpose: "Read live SAFRS status without changing the task registry.",
    why: "Use this to see recorded tasks, approvals, and evidence.",
    effect: "Reads the registry and policy. It must not change task status.",
    expected:
      "A current governance summary, or a report that the data is not yet available.",
    next: "If an active task or pending approval exists, open Tasks or Governance.",
    command: "pnpm saf:status",
    source: "package.json → tools/status",
    category: "governance",
    risk: "R0",
    safety: "safe",
    mutation: false,
    approval: "Not required. Read-only operation.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation:
      "This action only reads. This board does not see the registry on the local machine.",
  },
  {
    id: "task-list",
    name: "List Tasks",
    purpose: "Show the tasks recorded in the repository control plane.",
    why: "Use this to see work that is claimed or already closed.",
    effect: "Reads the task registry. It does not change status.",
    expected: "A task list, or an empty list if nothing has been recorded.",
    next: "If a task is active, do not claim overlapping work in the same workspace.",
    command: "pnpm task list",
    source: "package.json → tools/task",
    category: "tasks",
    risk: "R0",
    safety: "safe",
    mutation: false,
    approval: "Not required. Read-only operation.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation: "This action only reads the task registry.",
  },
  {
    id: "setup",
    name: "Prepare Local Environment",
    purpose:
      "Create the environment file and prepare a disposable local database.",
    why: "Use this if readiness says the environment is incomplete.",
    effect: "Changes local files and may start local PostgreSQL.",
    expected:
      "The environment file is present and the local database is ready to use.",
    next: "Run Check Readiness, then Start Local App if everything is safe.",
    command: "pnpm setup",
    source: "package.json → scripts/setup.mjs",
    category: "maintenance",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval:
      "Human approval is not required, but confirmation is still required.",
    timeout: "May take several minutes if Docker and Prisma are not ready.",
    executableHere: false,
    confirmation:
      "This action changes the local machine. Continue only on a work computer, never in production, and never from this board.",
  },
  {
    id: "dev",
    name: "Start Local App",
    purpose:
      "Start the local Golden Path: database, typed API, and web on this computer.",
    why: "Use this to see the product working without deploying anything.",
    effect: "Starts local services. It does not deploy to production.",
    expected:
      "The local app is available on this computer after the prerequisites pass.",
    next: "If it fails, run Check Readiness. Do not treat this as a release.",
    command: "pnpm dev",
    source: "package.json → scripts/dev.mjs",
    category: "development",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval: "Human approval is not required. It remains local.",
    timeout: "May take several minutes when services first start.",
    executableHere: false,
    confirmation:
      "This action starts services on the local computer. Production remains blocked.",
  },
  {
    id: "test",
    name: "Run Tests",
    purpose: "Run the supported repository test suite.",
    why: "Use this before treating a change as safe.",
    effect: "Runs tests. It does not change production data.",
    expected: "A pass or fail report from the existing test suite.",
    next: "If it fails, read the report and fix the cause. Do not weaken the tests.",
    command: "pnpm test",
    source: "package.json → scripts/test.mjs",
    category: "testing",
    risk: "R1",
    safety: "caution",
    mutation: false,
    approval: "Human approval is not required.",
    timeout: "May take several minutes.",
    executableHere: false,
    confirmation:
      "This action runs tests on the local machine. The results are not visible on this board.",
  },
  {
    id: "check",
    name: "Run Full Quality Check",
    purpose:
      "Run governance, token, lint, type, test, and build checks in sequence.",
    why: "Use this before requesting review or releasing a change.",
    effect: "Runs quality checks. It does not deploy.",
    expected:
      "Every local gate passes, or the run stops at the first failing gate.",
    next: "If it fails, repair the gate that stopped. Do not bypass it.",
    command: "pnpm check",
    source: "package.json",
    category: "quality",
    risk: "R1",
    safety: "caution",
    mutation: false,
    approval: "Human approval is not required.",
    timeout: "Longer than an ordinary test run.",
    executableHere: false,
    confirmation:
      "This action runs the full quality check on the local machine.",
  },
  {
    id: "governance",
    name: "Check Governance",
    purpose: "Verify the executable SAFRS rules in the repository.",
    why: "Use this to confirm that controls have not been weakened.",
    effect: "Runs governance verification. It does not change policy.",
    expected: "A passing report, or a list of controls that are not yet met.",
    next: "If it fails, do not treat the repository as Controlled or Secure.",
    command: "pnpm governance",
    source: "package.json → scripts/safrs-verify.mjs",
    category: "governance",
    risk: "R1",
    safety: "caution",
    mutation: false,
    approval: "Human approval is not required.",
    timeout: "Several minutes.",
    executableHere: false,
    confirmation:
      "This action only verifies governance. It does not raise the conformance level.",
  },
  {
    id: "db-start",
    name: "Start Local Database",
    purpose: "Start disposable local PostgreSQL.",
    why: "Use this if the local app needs a database and Docker is already running.",
    effect:
      "Starts the local Postgres container. It does not touch production data.",
    expected: "Local PostgreSQL is ready on this machine.",
    next: "If it fails, open Docker Desktop and check readiness again.",
    command: "pnpm db:start",
    source: "package.json → docker compose postgres",
    category: "database",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval: "Human approval is not required. Local only.",
    timeout: "Until the container is ready.",
    executableHere: false,
    confirmation: "This action only starts the disposable local database.",
  },
  {
    id: "db-stop",
    name: "Stop Local Database",
    purpose: "Stop local PostgreSQL without implicitly deleting the volume.",
    why: "Use this when local services are not in use.",
    effect: "Stops the local Postgres container.",
    expected: "The local database stops responding.",
    next: "Start it again before running the local app.",
    command: "pnpm db:stop",
    source: "package.json → docker compose stop postgres",
    category: "database",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval: "Human approval is not required. Local only.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation:
      "This action stops the local database. The local app will no longer be able to write data.",
  },
  {
    id: "db-migrate",
    name: "Apply Local Database Schema",
    purpose: "Apply Prisma migrations to the local database.",
    why: "Use this after the schema changes or after setup.",
    effect: "Changes the local database schema.",
    expected: "The local database matches the recorded schema.",
    next: "If sample data is needed, run Seed Sample Data.",
    command: "pnpm db:migrate",
    source: "package.json → @safrs/database migrate",
    category: "database",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval:
      "Human approval is not required if the target remains disposable.",
    timeout: "Several minutes.",
    executableHere: false,
    confirmation:
      "This action changes the local database schema. Do not point it at a production database.",
  },
  {
    id: "db-seed",
    name: "Seed Sample Data",
    purpose: "Load the local database with supported sample data.",
    why: "Use this to see the Golden Path working with one concrete example.",
    effect: "Writes sample data to the local database.",
    expected: "Sample data is available in the local app.",
    next: "Start the local app and open the readiness table.",
    command: "pnpm db:seed",
    source: "package.json → @safrs/database seed",
    category: "database",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval:
      "Human approval is not required if the target remains disposable.",
    timeout: "Several minutes.",
    executableHere: false,
    confirmation: "This action writes sample data to the local database only.",
  },
  {
    id: "db-reset",
    name: "Reset Local Database",
    purpose: "Empty and rebuild the disposable local database.",
    why: "Use this only if the local data may be discarded.",
    effect:
      "Deletes local data and rebuilds the schema. Rejected if the URL is not disposable.",
    expected:
      "An empty local database with a fresh schema, or a rejection if the target is unsafe.",
    next: "Seed sample data again if the readiness table needs it.",
    command: "pnpm db:reset",
    source: "package.json → @safrs/database reset + reset-guard",
    category: "database",
    risk: "R2",
    safety: "destructive",
    mutation: true,
    approval:
      "Explicit confirmation is required. The reset guard rejects a non-disposable URL.",
    timeout: "Several minutes.",
    executableHere: false,
    confirmation:
      "This action deletes local data. Continue only if the database is disposable and Chief accepts the loss of sample data.",
  },
  {
    id: "db-studio",
    name: "Open Local Database Studio",
    purpose: "Open the Prisma view for the local database.",
    why: "Use this to inspect the database without writing code.",
    effect: "Opens a local tool. It does not deploy.",
    expected: "Studio opens against the local database.",
    next: "Do not point this tool at a production database.",
    command: "pnpm db:studio",
    source: "package.json → @safrs/database studio",
    category: "database",
    risk: "R1",
    safety: "caution",
    mutation: false,
    approval: "Human approval is not required. It remains local.",
    timeout: "Until Studio opens.",
    executableHere: false,
    confirmation: "This action opens a local database tool, not production.",
  },
  {
    id: "capability-preview",
    name: "Preview Capability",
    purpose: "See what would happen if an optional capability were enabled.",
    why: "Use this before enabling email or Stripe.",
    effect: "Preview only. It does not change the project.",
    expected:
      "A summary of the changes that would occur if the capability were enabled.",
    next: "If the preview is accepted, enable it with explicit confirmation on the local machine.",
    command: "pnpm capability:add --preview",
    source: "package.json → tools/capabilities",
    category: "projects",
    risk: "R0",
    safety: "safe",
    mutation: false,
    approval: "Not required. This is a preview.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation:
      "This action only shows a preview. It does not enable the capability.",
  },
  {
    id: "capability-apply",
    name: "Enable Capability",
    purpose: "Enable a recorded capability after explicit confirmation.",
    why: "Use this only after the preview is understood.",
    effect:
      "Changes the project so the recorded capability is marked enabled. This is not proof that the external service is installed.",
    expected:
      "The capability is recorded on the project, or rejected if confirmation is incorrect.",
    next: "Check readiness and run the project tests. Do not assume email or Stripe is live.",
    command:
      'pnpm capability:add --apply --confirm "ENABLE <id> FOR <project>"',
    source: "package.json → tools/capabilities",
    category: "projects",
    risk: "R2",
    safety: "approval",
    mutation: true,
    approval: "Explicit confirmation with the exact phrase is required.",
    timeout: "Several minutes.",
    executableHere: false,
    confirmation:
      "This action changes the project. Recording email or Stripe as R2 is not proof that the service is installed and running.",
  },
  {
    id: "dev-email",
    name: "Preview Local Email",
    purpose: "Open the local email preview for the web package.",
    why: "Use this only when the email capability is actually being worked on.",
    effect:
      "Starts the local email preview. It does not send production email.",
    expected:
      "The local email preview opens, or it fails if the package is not prepared.",
    next: "Do not treat this as real email delivery.",
    command: "pnpm dev:email",
    source: "package.json → @safrs/web dev:email",
    category: "development",
    risk: "R1",
    safety: "caution",
    mutation: false,
    approval: "Human approval is not required. It remains local.",
    timeout: "Until the preview opens.",
    executableHere: false,
    confirmation: "This action only opens the local email preview.",
  },
  {
    id: "stripe-listen",
    name: "Listen to Local Stripe",
    purpose: "Forward Stripe test events to the local app.",
    why: "Use this only when testing the payment capability locally.",
    effect:
      "Opens a local test channel. It does not process production payments.",
    expected:
      "The test channel is active, or it fails if the Stripe CLI and test secrets are unavailable.",
    next: "Do not point this at production keys or webhooks.",
    command: "pnpm stripe:listen",
    source: "package.json → @safrs/web stripe:listen",
    category: "development",
    risk: "R2",
    safety: "approval",
    mutation: false,
    approval: "Test environments only. Do not use production credentials.",
    timeout: "Runs for as long as the test channel remains open.",
    executableHere: false,
    confirmation:
      "This action is for Stripe test use only. Production remains forbidden.",
  },
  {
    id: "task-claim",
    name: "Claim Task",
    purpose: "Record that one piece of work is now owned and may be mutated.",
    why: "Use this before changing code, so work does not collide with another claim.",
    effect: "Writes to the shared task registry.",
    expected:
      "The task moves to an active state, or it is rejected if it overlaps.",
    next: "Continue to plan or execute, according to the allowed transition.",
    command:
      "pnpm task claim --id ID --title TITLE --owner-id ID --owner-label LABEL --risk R0|R1|R2|R3 --scope PATH",
    source: "package.json → tools/task",
    category: "tasks",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval:
      "Confirmation is required. Overlapping claims on the same workspace are not allowed.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation:
      "This action writes to the task registry. Do not claim overlapping work.",
  },
  {
    id: "task-state",
    name: "Change Task Status",
    purpose: "Move a task to the next allowed state.",
    why: "Use this so the work trail stays honest.",
    effect: "Changes the task status in the shared registry.",
    expected:
      "The new status is recorded, or it is rejected if the transition is invalid.",
    next: "If it enters REVIEW, prepare the required evidence and approval.",
    command: "pnpm task state --id ID --to STATE",
    source: "package.json → tools/task",
    category: "tasks",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval: "Confirmation is required. The transition must be valid.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation:
      "This action changes task status. Invalid transitions will be rejected.",
  },
  {
    id: "task-close",
    name: "Close Task",
    purpose: "Close a task that is finished or will not continue.",
    why: "Use this so the registry does not hold completed work open.",
    effect: "Changes the task status to closed according to the close rules.",
    expected: "The task is closed, or it is rejected if it may not close yet.",
    next: "Review the task list so no unnecessary active claim remains.",
    command: "pnpm task close --id ID",
    source: "package.json → tools/task",
    category: "tasks",
    risk: "R1",
    safety: "caution",
    mutation: true,
    approval: "Confirmation is required.",
    timeout: "A few seconds.",
    executableHere: false,
    confirmation: "This action closes the task in the shared registry.",
  },
  {
    id: "deploy-production",
    name: "Deploy Production",
    purpose: "Prepare or run a production operation with real consequences.",
    why: "Shown so the authority limit is visible, not so it can be clicked.",
    effect:
      "Unavailable on this board. Agents must not deploy production directly.",
    expected:
      "Blocked. R3 operations may only be prepared, then authorized separately by a human.",
    next: "Do not look for a shortcut. Production remains outside this board.",
    command: "Not exposed. R3 remains prepare-only until human authorization.",
    source: "SAFRS_SPEC.md, AGENTS.md, .safrs/policy.json",
    category: "deployment",
    risk: "R3",
    safety: "destructive",
    mutation: true,
    approval:
      "Human authorization is required for the exact operation proposed.",
    timeout: "Not executed here.",
    executableHere: false,
    confirmation:
      "This action is blocked. This board does not deploy production.",
  },
];

export function actionById(id: string) {
  return ACTIONS.find((action) => action.id === id);
}
