/**
 * Emit a typed fetch-wrapper module over the Hono RPC client. The wrapper adds
 * a timeout and a single retry-on-network-error, and normalizes errors to a
 * standard envelope. The Hono client still provides static request/response
 * types; this module layers runtime resilience on top.
 *
 * @param {{clientImport?: string}} options
 * @returns {string} TypeScript module source
 */
export function renderClientModule({
  clientImport = "@safrs/api/client",
} = {}) {
  return `// Generated by @safrs/codegen --client. Do not edit by hand.
import { createApiClient } from "${clientImport}";

export type ApiCallOptions = {
  timeoutMs?: number;
  retries?: number;
};

export type ApiResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: { status: number; body: unknown } };

const DEFAULT_TIMEOUT_MS = 10_000;
const DEFAULT_RETRIES = 1;

export function createTypedClient(baseUrl: string, options: ApiCallOptions = {}) {
  const client = createApiClient(baseUrl);
  const timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const retries = options.retries ?? DEFAULT_RETRIES;

  async function withTimeout<T>(task: Promise<Response>): Promise<Response> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    try {
      return await task;
    } finally {
      clearTimeout(timer);
    }
  }

  async function run<T>(call: () => Promise<{ response: Response; data: T }>): Promise<ApiResult<T>> {
    let lastError: unknown;
    for (let attempt = 0; attempt <= retries; attempt += 1) {
      try {
        const { response, data } = await call();
        if (!response.ok) {
          return { ok: false, error: { status: response.status, body: data } };
        }
        return { ok: true, value: data };
      } catch (error) {
        lastError = error;
        if (attempt < retries) continue;
      }
    }
    throw new Error("request failed", { cause: lastError });
  }

  return { client, withTimeout, run };
}
`;
}
