import { en, Faker } from "@faker-js/faker";
import { mockForSchema } from "./schemas.mjs";

const faker = new Faker({ locale: en });

/**
 * Generate a deterministic mock value for a schema name.
 *
 * @param {Array<{name: string, schema: import("zod").ZodTypeAny}>} schemas
 * @param {string} name
 * @param {object} [overrides] partial values merged over the generated mock
 * @returns {unknown}
 */
export function generateMock(schemas, name, overrides = {}) {
  const found = schemas.find((s) => s.name === name);
  if (!found) throw new Error(`Unknown schema: ${name}`);
  const base = mockForSchema(found.schema, faker);
  if (base && typeof base === "object" && !Array.isArray(base)) {
    return { ...base, ...overrides };
  }
  return overrides && Object.keys(overrides).length ? overrides : base;
}

/**
 * Emit a standalone mock-data module. Each factory imports the live schema
 * objects and produces a realistic mock via a runtime faker walker, so the
 * generated file stays correct as schemas evolve.
 *
 * @param {Array<{name: string, schema: import("zod").ZodTypeAny}>} schemas
 * @param {{schemaImport?: string}} options
 * @returns {string} JavaScript module source
 */
export function renderMockModule(
  schemas,
  { schemaImport = "../../packages/schemas/src/index.js" } = {},
) {
  const ids = schemas.map((s) => s.name);
  const lines = [
    "// Generated by @safrs/codegen --mock. Do not edit by hand.",
    'import { Faker, en } from "@faker-js/faker";',
    `import * as schemas from "${schemaImport}";`,
    "",
    "const faker = new Faker({ locale: en });",
    "",
    "function walk(schema, depth = 0) {",
    '  if (depth > 6) return "";',
    '  const kind = String(schema?._def?.type ?? "").toLowerCase();',
    "  switch (kind) {",
    '    case "string": return faker.lorem.word();',
    '    case "number": return faker.number.int({ min: 1, max: 1000 });',
    '    case "boolean": return faker.datatype.boolean();',
    '    case "date": return faker.date.recent().toISOString();',
    '    case "object": {',
    "      const shape = schema._def.shape ?? {};",
    "      const out = {};",
    "      for (const key of Object.keys(shape)) out[key] = walk(shape[key], depth + 1);",
    "      return out;",
    "    }",
    '    case "optional":',
    '    case "nullable": return walk(schema._def.innerType, depth + 1);',
    '    case "enum": return (schema._def.values || schema._def.options || [])[0] ?? "";',
    '    case "literal": return schema._def.value;',
    '    case "array": return [walk(schema._def.type ?? schema._def.items, depth + 1)];',
    '    default: return "";',
    "  }",
    "}",
    "",
  ];
  for (const id of ids) {
    const fn = `mock${id.replace(/[^A-Za-z0-9]/g, "")}`;
    lines.push(`export function ${fn}(overrides = {}) {`);
    lines.push(`  const base = walk(schemas.${id});`);
    lines.push(
      '  return typeof base === "object" && base ? { ...base, ...overrides } : overrides;',
    );
    lines.push("}");
    lines.push("");
  }
  lines.push(`export const mockableSchemas = ${JSON.stringify(ids)};`);
  return lines.join("\n");
}
